application: yomusu
version: 2
runtime: python
api_version: 1

handlers:
- url: /(favicon.ico)
  static_files: static/img/\1
  upload: static/img/favicon.ico

- url: /css/(.*\.css)
  static_files: templates/css/\1
  upload: templates/css/(.*\.css)

- url: /js/(.*\.js)
  static_files: templates/js/\1
  upload: templates/js/(.*\.js)

- url: .*
  script: django_bootstrap.py
